sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - gcc-6
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
script:
  - gcc --version
  - g++ --version
  - make testfastiota
  - make testfastiotaho
  - ./testfastiota
  - ./testfastiotaho
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
